services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: safe-password
      POSTGRES_DB: teamtasks_db
    ports:
      - "5432:5432"
  cache:
    image: redis:alpine
    ports:
      - "6379:6379"
  queue:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Communication
      - "15672:15672" # Web UI

  logs:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
    ports:
      - "8081:80"

  api:
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
      - cache
      - queue
